# version: 0.2
# phases:
#   install:
#     runtime-versions:
#       python: 3.8
#     commands:
#       - echo "Installing dependencies..."
#       - pip install -r requirements.txt -t lib
#   build:
#     commands:
#       - echo "Zipping deployment package..."
#       - cd lib
#       - zip -r9 ../deployment_package.zip .
#       - cd ..
#       - zip -g deployment_package.zip lambda_function.py
#   post_build:
#     commands:
#       - echo "Updating lambda Function..."
#       - aws lambda update-function-code --function-name github-to-lambda-demo --zip-file fileb://deployment_package.zip
#       - echo "DONE!!"
      
version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib || exit 1
      - pip install pandas-1.4.2-cp310-cp310-win32.whl
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package.zip . || exit 1
      - cd ..
      - zip -g deployment_package.zip lambda_function.py || exit 1
  post_build:
    commands:
      - echo "Updating Lambda function..."
      - aws lambda update-function-code --function-name github-to-lambda-demo --zip-file fileb://deployment_package.zip || exit 1
      - echo "Updating Lambda function configuration..."
      - aws lambda update-function-configuration --function-name github-to-lambda-demo --layers arn:aws:lambda:us-east-1:289222008732:function:github-to-lambda-demo || exit 1
      - echo "DONE!!"
